driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazon-linux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6.9
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.9
  - name: debian-9.0
  - name: fedora-25
  - name: freebsd-10.3
  - name: freebsd-11.0
  - name: opensuse-leap-42.3
  - name: sles-12-sp1
    driver:
      box: chef/sles-12-sp1-x86_64 # private box
  - name: solaris-10.11
    driver:
      box: chef/solaris-10.11 # private box
  - name: solaris-11.3
    driver:
      box: chef/solaris-11.3 # private box
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: windows-2008r2
    driver:
      box: chef/windows-server-2008r2-standard # private box
  - name: windows-2012r2
    driver:
      box: chef/windows-server-2012r2-standard # private box

suites:
- name: service_bsd
  run_list:
  - recipe[test::service]
  includes: ["freebsd-10.3", "freebsd-11.0"]

- name: service_init
  run_list:
  - recipe[test::service]
  includes: ["centos-6.9", "debian-7.11", "amazon-linux", "sles-12-sp1"]

- name: service_systemd
  run_list:
  - recipe[test::service]
  includes: ["centos-7.3", "debian-8.9", "debian-9.0", "fedora-25", "ubuntu-16.04", "opensuse-leap-42.3"]

- name: service_upstart
  run_list:
  - recipe[test::service]
  includes: ["ubuntu-14.04"]

- name: service_smf
  run_list:
  - recipe[test::service]
  includes: ["solaris-11.3", "solaris-10.11"]

- name: cron
  run_list:
  - recipe[test::cron]
  excludes: ["windows-2008r2", "windows-2012r2"]

- name: timer_systemd
  run_list:
  - recipe[chef-client::systemd_service]
  attributes:
    chef_client:
      systemd:
        timer: true
  includes: ["centos-7.3", "debian-8.9", "debian-9.0", "fedora-25", "ubuntu-16.04"]

- name: config
  run_list:
  - recipe[test::config]

- name: delete_validation
  run_list:
  - recipe[chef-client::delete_validation]

# Test that the we can use the cron_d directory
- name: cook-use_cron_d
  run_list:
  - recipe[test::cook-use_cron_d]
  excludes: ["windows-2008r2", "windows-2012r2"]

- name: task
  run_list:
    - recipe[test::task]
  includes: ["windows-2008r2", "windows-2012r2"]
