driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

transport:
  name: winrm
  elevated: true

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: pester

platforms:
  - name: windows-8.1
    driver_config:
      box: chef/windows-8.1-professional
  - name: windows-10
    driver_config:
      box: chef/windows-10-enterprise
  - name: windows-2008r2
    driver_config:
      box: chef/windows-server-2008r2-standard
  - name: windows-2012r2
    driver_config:
      box: chef/windows-server-2012r2-standard
  - name: windows-2012r2-chef-12.6
    driver_config:
      box: chef/windows-server-2012r2-standard
    provisioner:
      require_chef_omnibus: 12.6.0

suites:
  - name: autorun
    run_list:
      - recipe[test::autorun]
  - name: certificate
    run_list:
      - recipe[test::certificate]
  - name: feature
    run_list:
      - recipe[test::feature]
  - name: font
    run_list:
      - recipe[test::font]
  - name: http_acl
    run_list:
      - recipe[test::http_acl]
  - name: package
    run_list:
      - recipe[test::package]
  - name: pagefile
    run_list:
      - recipe[test::pagefile]
  - name: path
    run_list:
      - recipe[test::path]
  - name: share
    run_list:
      - recipe[test::share]
  - name: shortcut
    run_list:
      - recipe[test::shortcut]
  - name: tasks
    run_list:
      - recipe[test::tasks]
  - name: zipfile
    run_list:
      - recipe[test::zipfile]
